name: next-blog

services:
  cache:
    image: valkey/valkey:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: valkey-server --save 60 1 --loglevel warning --requirepass mypassword
    volumes:
      - cache:/data

volumes:
  cache:

