export const siteMetadata = {
  title: "Next.js Blog With Tailwind",
  author: "ibqn",
  headerTitle: "Next.js Blog",
  description: "A blog created with Next and Tailwind.",
  language: "en-us",
  theme: "dark",
  siteUrl: "http://localhost:3000",
  siteLogo: "/logo.png",
  socialBanner: "/social-banner.png",
  email: "ibqn@gmail.com",
  github: "https://github.com/ibqn",
  twitter: "https://twitter.com",
  facebook: "https://facebook.com",
  youtube: "https://youtube.com",
  linkedin: "https://www.linkedin.com",
  dribbble: "https://www.dribbble.com",
  locale: "en-US",
}
